#!/usr/bin/env python3
"""Restore model text records, then let installed msprof generate its native report.

No JSON event, duration, color, or dependency is generated by this script.
Binary layout follows npu-simulator/cannsim/core/public/instr_decoder.py.
The two spaces between decode and execution fields follow the model's text
formatter and msopprof's parser; the upstream Python decoder uses one space,
which this installed msprof silently fails to parse as instruction detail.
"""
import argparse
import collections
import hashlib
import json
import mmap
import os
from pathlib import Path
import struct
import subprocess


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('raw_file', type=Path, help='One chip instr.bin; chips must be exported separately')
    p.add_argument('--output', type=Path, required=True, help='New directory')
    p.add_argument('--core-id', default='0', help='Comma-separated core numbers, or all')
    p.add_argument('--soc-version', default='Ascend950PR_9589')
    a = p.parse_args()
    raw = a.raw_file.resolve(strict=True)
    wanted = None if a.core_id == 'all' else {int(x) for x in a.core_id.split(',')}
    if wanted is not None and (not wanted or min(wanted) < 0 or max(wanted) >= 32):
        p.error('This 950PR case uses local core IDs 0..31')
    out = a.output.resolve()
    out.mkdir(parents=True, mode=0o700, exist_ok=False)
    dump = out / 'dump'
    dump.mkdir(mode=0o700)
    record = struct.Struct('<QIIQB200s200s7x')
    if not raw.stat().st_size or raw.stat().st_size % record.size:
        raise ValueError('Empty or incomplete binary record file')
    counts = collections.Counter()
    streams = {}
    try:
        with raw.open('rb') as stream, mmap.mmap(stream.fileno(), 0, access=mmap.ACCESS_READ) as mm:
            digest = hashlib.sha256(mm).hexdigest()
            for tick, core, sub, pc, kind, dec, exe in record.iter_unpack(mm):
                core %= 32
                if wanted is not None and core not in wanted:
                    continue
                if sub not in (0, 1, 2) or kind not in (0, 1):
                    raise ValueError(f'Unsupported raw record: sub={sub}, kind={kind}')
                unit = ('cubecore0', 'veccore0', 'veccore1')[sub]
                suffix = 'instr_popped_log' if kind else 'instr_log'
                name = f'core{core}.{unit}.{suffix}.dump'
                if name not in streams:
                    streams[name] = (dump / name).open('w', encoding='utf-8')
                    os.chmod(dump / name, 0o600)
                dec = dec.split(b'\0', 1)[0].decode('utf-8')
                exe = exe.split(b'\0', 1)[0].decode('utf-8')
                line = f'[info] {dec}' if '++++++++++++++++++++++' in dec else f'[info] [{tick:08d}] {dec}  {exe}'
                streams[name].write(line + '\n')
                counts[name] += 1
    finally:
        for stream in streams.values():
            stream.close()
    if not counts:
        raise ValueError('No records selected')
    cmd = ['msprof', 'op', 'simulator', '--export', str(dump), '--output', str(out / 'output'),
           '--soc-version=' + a.soc_version, '--aic-metrics=PipeUtilization,ResourceConflictRatio']
    if wanted is not None:
        cmd += ['--core-id=' + '|'.join(map(str, sorted(wanted)))]
    with (out / 'export.log').open('w') as log:
        result = subprocess.run(cmd, stdout=log, stderr=subprocess.STDOUT, timeout=180)
    reports = list((out / 'output').glob('OPPROF_*/simulator/trace.json'))
    manifest = dict(raw_file=str(raw), raw_sha256=digest, records_by_file=dict(counts),
                    command=cmd, returncode=result.returncode,
                    reports=[str(x.relative_to(out)) for x in reports])
    (out / 'export_manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    if result.returncode or len(reports) != 1 or 'Profiling data parse finished.' not in (out / 'export.log').read_text():
        raise RuntimeError(f'Native export failed; see {out / "export.log"}')
    data = json.loads(reports[0].read_text())
    if not any(e.get('ph') == 'X' for e in data.get('traceEvents', [])):
        raise RuntimeError('Native report contains no duration events')
    flags = [e for e in data['traceEvents'] if e.get('ph') == 'B' and e.get('name') in ('SET_FLAG', 'WAIT_FLAG')]
    if any(not e.get('args', {}).get('detail') for e in flags):
        raise RuntimeError('Native parser lost synchronization details')
    print(reports[0])


if __name__ == '__main__':
    main()
